/* GO's retained four-model transitional showroom */
const goFleet=[
 {name:'BYD Qin L DM-i',image:'/assets/qin.webp',interior:null,power:'Plug-in hybrid',role:'Phase 1–2 workhorse',tag:'HYBRID REFERENCE',word:'HYBRID',platform:'DM-i plug-in hybrid sedan',energy:'Electric drive with fuel flexibility',use:'Urban trips and longer operating corridors',source:'https://www.byd.com/cn/dynasty-home/models/qin/26-qin-l-dm-i.html'},
 {name:'BYD Atto 3 / Yuan Plus',image:'/assets/atto-cutout.webp',interior:'/assets/atto-interior.webp',power:'Battery electric',role:'GO Green / EV pilot',tag:'EV REFERENCE',word:'ELECTRIC',platform:'Battery-electric compact SUV',energy:'Rechargeable battery-electric platform',use:'Urban EV pilot and charging integration',source:'https://www.byd.com/en/car/atto3'},
 {name:'Geely Galaxy EX5',image:'/assets/ex5.webp',interior:'/assets/ex5-interior.webp',power:'Battery electric',role:'Electric fleet candidate',tag:'FLEET CANDIDATE',word:'ELECTRIC',platform:'Battery-electric SUV',energy:'Dedicated electric-drive platform',use:'Future electric fleet evaluation',source:'https://www.geely.com/en/models/ex5'},
 {name:'Chery Exeed / RX',image:'/assets/chery-exeed-rx-cutout.webp',interior:'/assets/exeed-interior.webp',power:'Platform under evaluation',role:'Hybrid / electric candidate',tag:'FLEET CANDIDATE',word:'NEXT',platform:'EXEED RX exterior model reference',energy:'Final powertrain and trim under evaluation',use:'Premium fleet sourcing candidate',source:'https://www.exeedinternational.com/global/rx/'}
];
let carIndex=0,carView='exterior',carBusy=false;
const carImage=$('#showroomCar');
function renderCar(){const f=goFleet[carIndex];$$('[data-car]').forEach((b,i)=>{b.setAttribute('aria-selected',String(i===carIndex));b.tabIndex=i===carIndex?0:-1;});$('#carName').textContent=f.name;$('#carPower').textContent=f.power;$('#carRole').textContent=f.role;$('#carTag').textContent=f.tag;$('.showroom-word').textContent=f.word;$('#specPlatform').textContent=f.platform;$('#specEnergy').textContent=f.energy;$('#specUse').textContent=f.use;$('#specSource').href=f.source;const inButton=$('[data-view="interior"]');inButton.hidden=!f.interior;if(!f.interior)carView='exterior';$$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===carView)));$('#showroomStage').classList.toggle('interior',carView==='interior');carImage.src=carView==='interior'?f.interior:f.image;carImage.alt=f.name+' '+carView+' manufacturer reference';}
function selectCar(i){if(carBusy)return;carBusy=true;carIndex=(i+4)%4;if(RM){renderCar();carBusy=false;return;}gsap.to(carImage,{opacity:0,x:-65,duration:.2,onComplete:()=>{renderCar();gsap.fromTo(carImage,{opacity:0,x:85,rotationY:8},{opacity:1,x:0,rotationY:0,duration:.65,ease:'power3.out',onComplete:()=>carBusy=false});}});}
$$('[data-car]').forEach((b,i)=>{b.addEventListener('click',()=>selectCar(i));b.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const n=(i+(e.key==='ArrowRight'?1:3))%4;selectCar(n);$$('[data-car]')[n].focus();}});});
$('#prevCar').addEventListener('click',()=>selectCar(carIndex-1));$('#nextCar').addEventListener('click',()=>selectCar(carIndex+1));
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{carView=b.dataset.view;selectCar(carIndex)}));
let swipeStart=null;$('#showroomStage').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;swipeStart=e.clientX;});$('#showroomStage').addEventListener('pointerup',e=>{if(swipeStart!==null&&Math.abs(e.clientX-swipeStart)>60)selectCar(carIndex+(e.clientX<swipeStart?1:-1));swipeStart=null;});$('#showroomStage').addEventListener('pointercancel',()=>swipeStart=null);
$('#specToggle').addEventListener('click',()=>{const expanded=$('#specToggle').getAttribute('aria-expanded')==='true';$('#specToggle').setAttribute('aria-expanded',String(!expanded));$('#carSpecs').hidden=expanded;$('#specToggle span').textContent=expanded?'＋':'−';ScrollTrigger.refresh();});
renderCar();
